### NumPy Basics




In [24]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np

In [25]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array
array_1d = np.array([2, 4, 5, 6, 7, 9])
print(array_1d)
print(type(array_1d))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>


In [26]:
# Creating a 2-D array using two lists
array_2d = np.array([[2, 3, 4], [5, 8, 7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


In [28]:
array_2d.T

array([[2, 5],
       [3, 8],
       [4, 7]])

In [33]:
array_2d.shape

(2, 3)

In NumPy, dimensions are called **axes**. In the 2-d array above, there are two axes, having two and three elements respectively. 

In NumPy terminology, for 2-D arrays:
* ```axis = 0``` refers to the rows
* ```axis = 1``` refers to the columns

<img src="numpy_axes.jpg" style="width: 600px; height: 400px">

In [30]:
list_1 = [3, 6, 7, 5]
list_2 = [4, 5, 1, 7]

# the list way to do it: map a function to the two lists
product_list = list(map(lambda x, y: x*y, list_1, list_2))
print(product_list)


[12, 30, 7, 35]


In [31]:
# The numpy array way to do it: simply multiply the two arrays
array_1 = np.array(list_1)
array_2 = np.array(list_2)

array_3 = array_1*array_2
print(array_3)
print(type(array_3))

[12 30  7 35]
<class 'numpy.ndarray'>


As you can see, the NumPy way of multiplication is clearly more concise.

Even simple mathematical operations on lists require for loops, unlike with arrays. For example, to calculate the square of every number in a list:

In [6]:
# Square a list
list_squared = [i**2 for i in list_1]

# Square a numpy array
array_squared = array_1**2

print(list_squared)
print(array_squared)

[9, 36, 49, 25]
[ 9 36 49 25]


This was with 1-D arrays. You'll often work with 2-D arrays (matrices), where the difference would be even greater. With lists, you'll have to store matrices as lists of lists and loop through them. With NumPy, you simply multiply the matrices.

### Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```, as done above
* Initialise arrays of fixed size (when the size is known) 


In [7]:
# Convert lists or tuples to arrays using np.array()
# Note that np.array(2, 5, 6, 7) will throw an error - you need to pass a list or a tuple
array_from_list = np.array([2, 5, 6, 7]) 
array_from_tuple = np.array((4, 5, 8, 9))

print(array_from_list)
print(array_from_tuple)

[2 5 6 7]
[4 5 8 9]


In [32]:
array_from_list.shape

(4,)

The other common way is to initialise arrays. You do this when you know the size of the array beforehand.

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [8]:
# Tip: Use help to see the syntax when required
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            

In [9]:
# Creating a 5 x 3 array of ones
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Notice that, by default, numpy creates data type = float64
# Can provide dtype explicitly using dtype
np.ones((5, 3), dtype = np.int)

<ipython-input-10-fcbcd70123de>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((5, 3), dtype = np.int)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
# Creating array of zeros
np.zeros(4, dtype = np.int)

<ipython-input-11-95d99b66027d>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros(4, dtype = np.int)


array([0, 0, 0, 0])

In [12]:
# Array of random numbers
np.random.random([3, 4])

array([[0.51749644, 0.88847706, 0.1002272 , 0.36538555],
       [0.70802994, 0.32445627, 0.65053128, 0.90394445],
       [0.57697263, 0.82447468, 0.37067345, 0.10471137]])

In [13]:
# np.arange()
# np.arange() is the numpy equivalent of range()
# Notice that 10 is included, 100 is not, as in standard python lists

# From 10 to 100 with a step of 5
numbers = np.arange(10, 100, 5)
print(numbers)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [46]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
a=np.random.randint(0, 10, (10,12))
a

array([[0, 6, 6, 7, 4, 4, 5, 7, 4, 6, 1, 7],
       [4, 2, 5, 7, 8, 6, 0, 7, 1, 1, 0, 7],
       [3, 5, 6, 7, 0, 4, 0, 5, 3, 0, 1, 7],
       [2, 0, 4, 4, 9, 0, 8, 3, 6, 3, 8, 3],
       [3, 2, 2, 5, 2, 3, 1, 5, 5, 9, 2, 3],
       [4, 5, 3, 3, 4, 7, 4, 2, 2, 3, 9, 7],
       [4, 4, 2, 2, 8, 7, 0, 8, 3, 5, 3, 6],
       [4, 4, 7, 6, 2, 9, 5, 0, 6, 3, 2, 6],
       [7, 7, 3, 9, 1, 8, 6, 2, 5, 6, 0, 9],
       [3, 0, 2, 0, 1, 6, 6, 7, 9, 2, 1, 8]])

In [43]:
a.reshape(12,10) #can we convert this in 2,10
#a.reshape(30,4)#(60,2)(40,3)(1,120)

array([[2, 9, 4, 7, 6, 3, 8, 9, 9, 0],
       [6, 2, 3, 4, 7, 8, 9, 2, 0, 8],
       [5, 2, 0, 8, 0, 2, 2, 8, 6, 6],
       [7, 4, 9, 7, 5, 2, 1, 1, 1, 3],
       [1, 2, 5, 9, 0, 6, 6, 8, 9, 0],
       [2, 9, 2, 7, 4, 8, 2, 0, 5, 5],
       [4, 7, 7, 4, 8, 9, 9, 9, 4, 0],
       [1, 1, 6, 6, 7, 8, 6, 3, 4, 1],
       [7, 3, 5, 7, 3, 0, 9, 2, 7, 9],
       [7, 3, 6, 8, 2, 3, 4, 1, 1, 9],
       [1, 6, 8, 6, 9, 9, 1, 0, 0, 8],
       [7, 7, 3, 5, 1, 2, 7, 9, 2, 5]])

In [44]:
a.reshape(20,2)

ValueError: cannot reshape array of size 120 into shape (20,2)

In [47]:
a.itemsize

4

### Inspect the Structure and Content of Arrays

It is helpful to inspect the structure of numpy arrays, especially while working with large arrays. Some attributes of numpy arrays are:
* ```shape```: Shape of array (n x m)
* ```dtype```: data type (int, float etc.)
* ```ndim```: Number of dimensions (or axes)
* ```itemsize```: Memory used by each array elememnt in bytes


Let's say you are working with a moderately large array of size 1000 x 300. First, you would want to wrap your head around the basic shape and size of the array. 

In [15]:
# Initialising a random 1000 x 300 array
rand_array = np.random.random((1000, 300))

# Print the second row
print(rand_array[1, ])

[0.73421195 0.52021232 0.43370103 0.09766995 0.27068782 0.00736492
 0.39519387 0.35734817 0.66722933 0.03042298 0.89181088 0.29120564
 0.98873326 0.26157167 0.79975179 0.79626149 0.74703884 0.83519483
 0.85801478 0.95734193 0.07146784 0.78123285 0.44790249 0.7821397
 0.17566737 0.34604476 0.67604017 0.53881353 0.54838036 0.4238842
 0.25126443 0.02701504 0.74002245 0.77809562 0.69546888 0.5273599
 0.19186161 0.81725259 0.69624824 0.38998051 0.15940746 0.60017033
 0.16546747 0.68020606 0.37050423 0.34840571 0.98373355 0.23105621
 0.22250039 0.46229515 0.0269919  0.31693997 0.52944514 0.14655839
 0.16038673 0.82673876 0.26560602 0.02990505 0.16100897 0.21131412
 0.96593685 0.75980008 0.80764728 0.26264399 0.69887227 0.43468249
 0.5968204  0.90302968 0.24169067 0.38821682 0.15877246 0.11399211
 0.46591038 0.42178733 0.41385302 0.72873414 0.50994269 0.59597918
 0.67263971 0.91865282 0.62686929 0.91289763 0.78321105 0.04493141
 0.69451524 0.41800628 0.00428013 0.93709741 0.58068982 0.1716787

In [16]:
# Inspecting shape, dtype, ndim and itemsize
print("Shape: {}".format(rand_array.shape))
print("dtype: {}".format(rand_array.dtype))
print("Dimensions: {}".format(rand_array.ndim))
print("Item size: {}".format(rand_array.itemsize))

Shape: (1000, 300)
dtype: float64
Dimensions: 2
Item size: 8


Reading 3-D arrays is not very obvious, because we can only print maximum two dimensions on paper, and thus they are printed according to a specific convention. Printing higher dimensional arrays follows the following conventions:
* The last axis is printed from left to right
* The second-to-last axis is printed from top to bottom
* The other axes are also printed top-to-bottom, with each slice separated by another using an empty line 

Let's see some examples.

In [36]:
# Creating a 2-D array using two lists
array_2d = np.array([[2, 3, 4], [5, 8, 7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


In [48]:
# Creating a 3-D array
# reshape() simply reshapes a 1-D array 
array_3d = np.arange(24).reshape(2, 3, 4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [51]:
# Creating a 3-D array
# reshape() simply reshapes a 1-D array 
array_3d = np.arange(24).reshape(2, 2,2, 3)
print(array_3d)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

np.full(): Create a constant array of any number ‘n’

np.tile(): Create a new array by repeating an existing array for a particular number of times

np.eye(): Create an identity matrix of any dimension

np.random.randint(): Create a random array of integers within a particular range 


In [19]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [53]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [21]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

# Compare Computation Times in NumPy and Standard Python Lists

Let's compare the computation times of arrays and lists for a simple task of calculating the element-wise product of numbers.


In [23]:

## Comparing time taken for computation
list_1 = [i for i in range(1000000)]
list_2 = [j**2 for j in range(1000000)]

# list multiplication
import time

# store start time, time after computation, and take the difference
t0 = time.time()
product_list = list(map(lambda x, y: x*y, list_1, list_2))
t1 = time.time()
list_time = t1 - t0 
print(t1-t0)

# numpy array 
array_1 = np.array(list_1)
array_2 = np.array(list_2)

t0 = time.time()
array_3 = array_1*array_2
t1 = time.time()
numpy_time = t1 - t0

print(t1-t0)

print("The ratio of time taken is {}".format(list_time/numpy_time))
0.13862943649291992
0.00394892692565918


0.3376150131225586
0.018850326538085938
The ratio of time taken is 17.91030051603764


0.00394892692565918

The ratio of time taken is 35.10559681217171
In this case, numpy is an order of magnitude faster than lists. This is with arrays of size in millions, but you may work on much larger arrays of sizes in order of billions. Then, the difference is even larger.

Some reasons for such difference in speed are:

NumPy is written in C, which is basically being executed behind the scenes
NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists
The following discussions demonstrate the differences in speeds of NumPy and standard python:

https://stackoverflow.com/questions/8385602/why-are-numpy-arrays-so-fast
https://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists