In [4]:
import numpy as np
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
b=np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19],
       [20, 21, 22, 23, 20, 21, 22, 23]])

In [17]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
b=np.array([1,2,3,4,5,6,7,8,9])
np.array_split(b,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [22]:
b[2]

3

In [23]:
b[1:6]

array([2, 3, 4, 5, 6])

In [24]:
b[1:8:2]

array([2, 4, 6, 8])

In [25]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[1, 1:4])#(row,col)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [26]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[0:2, 2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 8]


In [27]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[0:2,0:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3]
 [6 7 8]]


Example:
Input 1:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
 
Output 1:
[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]

#extract all border rows and column

In [28]:
import numpy as np
a=np.array([[11, 12, 13, 14],
[21, 22, 23, 24],
[31, 32, 33, 34]])

c1 = a[:, 0]
r1= a[0, :]
cl = a[:, -1]
rl = a[-1, :]

print(c1)
print(r1)
print(cl)
print(rl)

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


In [45]:
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]
ages.sort()
x = np.percentile(ages, 90)
print(ages)
print(x)

[2, 5, 6, 7, 8, 11, 15, 25, 27, 31, 31, 32, 36, 39, 41, 43, 48, 50, 61, 80, 82]
61.0


In [31]:
len(ages)

21

In [39]:
np.percentile(ages, 25)
np.percentile(ages, 95)
np.percentile(ages, 25)

11.0

In [38]:
21*0.25

5.25

In [ ]:
#make user define percentile function ,that will take list and percentile

In [43]:
import math
math.ceil(25.1)

26

In [48]:
#user define function in percentile
import math
def percentile(list, percent):
    list.sort()
    index=(len(list)*percent)/100#
    print(index)
    i=math.ceil(index)-1
    print(i)
    print(list[i])
    
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]
percentile(ages,25)

5.25
5
11
