In [4]:
import numpy as np
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
b=np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19],
       [20, 21, 22, 23, 20, 21, 22, 23]])

In [17]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
b=np.array([1,2,3,4,5,6,7,8,9])
np.array_split(b,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [22]:
b[2]

3

In [23]:
b[1:6]

array([2, 3, 4, 5, 6])

In [24]:
b[1:8:2]

array([2, 4, 6, 8])

In [25]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[1, 1:4])#(row,col)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [26]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[0:2, 2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 8]


In [27]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[0:2,0:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3]
 [6 7 8]]


Example:
Input 1:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
 
Output 1:
[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]

#extract all border rows and column

In [28]:
import numpy as np
a=np.array([[11, 12, 13, 14],
[21, 22, 23, 24],
[31, 32, 33, 34]])

c1 = a[:, 0]
r1= a[0, :]
cl = a[:, -1]
rl = a[-1, :]

print(c1)
print(r1)
print(cl)
print(rl)

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


In [45]:
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]
ages.sort()
x = np.percentile(ages, 90)
print(ages)
print(x)

[2, 5, 6, 7, 8, 11, 15, 25, 27, 31, 31, 32, 36, 39, 41, 43, 48, 50, 61, 80, 82]
61.0


In [31]:
len(ages)

21

In [39]:
np.percentile(ages, 25)
np.percentile(ages, 95)
np.percentile(ages, 25)

11.0

In [38]:
21*0.25

5.25

In [ ]:
#make user define percentile function ,that will take list and percentile

In [43]:
import math
math.ceil(25.1)

26

In [48]:
#user define function in percentile
import math
def percentile(list, percent):
    list.sort()
    index=(len(list)*percent)/100#
    print(index)
    i=math.ceil(index)-1
    print(i)
    print(list[i])
    
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]
percentile(ages,25)

5.25
5
11


In [22]:
import numpy as np
a=np.arange(30)
a=a.reshape(10,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [6]:
#how to print 10 in above array
a[3][1]

10

In [9]:
#change 19 with 100
a[6][1]=100
a

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18, 100,  20],
       [ 21,  22,  23],
       [ 24,  25,  26],
       [ 27,  28,  29]])

In [10]:
# could you replace 17 with 'lpu'
a[6][1]='lpu'

ValueError: invalid literal for int() with base 10: 'lpu'

In [23]:
a=a.astype('str')
a[6][1]='lpu'


In [25]:
a.shape

(10, 3)

In [27]:
a=np.array([str(x) for x in a])
a=np.char.replace(a,'100','lpu')
print(a)

["['0' '1' '2']" "['3' '4' '5']" "['6' '7' '8']" "['9' '10' '11']"
 "['12' '13' '14']" "['15' '16' '17']" "['18' 'lpu' '20']"
 "['21' '22' '23']" "['24' '25' '26']" "['27' '28' '29']"]


In [20]:
a.shape

(10,)

In [28]:
a.reshape(10,3)

ValueError: cannot reshape array of size 10 into shape (10,3)

In [ ]:
#will give some number as string format and retuen the string in reverse array format with float data type
#ex
#input='1 2 3 4 5 6 7'
#out=[7.0,6.0,5.0,4.0,3.0,2.0,1.0]

In [2]:
import numpy as np
a=input('enter string')

a=np.array(a.split()).astype('float')
a=a[::-1]
print(a)

enter string1 2 3 4 5 6 7
[7. 6. 5. 4. 3. 2. 1.]


In [3]:
l=list(map(float,input().split()))
l=l[::-1]
print(np.array(l))

1 2 3 4 5 6
[6. 5. 4. 3. 2. 1.]


In [ ]:
Checkerboard pattern:                                                   
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]
#print this pattern

In [4]:
import numpy as np
a=np.zeros((8,8),dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
a=np.zeros([8,8],dtype='int')
for i in range(8):
    if i%2==0:
        for j in range(8):
            if j%2!=0:
                a[i][j]=1
    else:
        for j in range(8):
            if j%2==0:
                a[i][j]=1

print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
arr=np.array([[0,1],[1,0]])
print(np.tile(arr,(8//2,8//2)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
The first line contains the space separated values of N and M.
The next  lines contains the space separated elements of M columns.

Output Format

First, print the transpose array and then print the flatten.

Sample Input

2 2
1 2
3 4   #[[1,2],
        [3,4]]
Sample Output

[[1 3]
 [2 4]]
[1 2 3 4]

In [13]:
N,M=map(int,input().split())
l=[]
for i in range(N):
    temp=list(map(int,input().split()))
    l.append(temp)

l=np.array(l)
print(l.transpose())
print(l.flatten())

3 4
1 2 3 4
2 3 4 5
4 5 6 7
[[1 2 4]
 [2 3 5]
 [3 4 6]
 [4 5 7]]
[1 2 3 4 2 3 4 5 4 5 6 7]
